In [ ]:
#Numpy crash course

In [1]:
import numpy as np
np.__version__

'2.3.5'

In [2]:
import sys
sys.version

'3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]'

# Creating List 

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

# below code we are converting list to array 

In [6]:
#pip install numpy

In [7]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
type(my_list)

list

In [10]:
np.  #we learn important function

SyntaxError: invalid syntax (2892284292.py, line 1)

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [13]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20,10)  #1st arg<2nd arg

array([], dtype=int64)

In [17]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [19]:
np.arange(-30,20)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [20]:
np.arange(10,10)

array([], dtype=int64)

In [21]:
np.arange()

TypeError: arange() requires stop to be specified.

In [22]:
np.arange(10,20,5)  #10-starting from -30 end point  5--step count

array([10, 15])

In [23]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [24]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [25]:
np.zeros(10)  #parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [27]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [28]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [29]:
zero=np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [30]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [34]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
np.zeros((5,10))  #bydefault large--will give row& 2nd arg-columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1))  #parameter tunning g

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [39]:
print(np.zeros(n,dtype=int))  #hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [40]:
n

(6, 7)

In [41]:
n1

(6, 8)

In [42]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
np.ones(3)

array([1., 1., 1.])

In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [46]:
np.ones(4)

array([1., 1., 1., 1.])

In [47]:
n

(6, 7)

In [48]:
np.ones(4)

array([1., 1., 1., 1.])

In [49]:
n

(6, 7)

In [50]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [51]:
np.ones((5,4),dtype=int)  #by default 5-rows  & 4- columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
np.t

AttributeError: module 'numpy' has no attribute 't'

In [53]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [54]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [55]:
np.ones(2)

array([1., 1.])

In [56]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [59]:
np.twos((2,4))

AttributeError: module 'numpy' has no attribute 'twos'

In [60]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [62]:
range(5)


range(0, 5)

In [63]:
r=range(5)
r

range(0, 5)

In [64]:
for i in r:
    print(i)

0
1
2
3
4


In [65]:
list(range(5))

[0, 1, 2, 3, 4]

In [66]:
range(1,10)

range(1, 10)

In [67]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [68]:
list(range(1,10,3))

[1, 4, 7]

In [69]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [70]:
rand(3,2)

NameError: name 'rand' is not defined

In [71]:
random.rand(3,2)

NameError: name 'random' is not defined

In [72]:
np.random.rand(5)

array([0.04240929, 0.60054567, 0.33437006, 0.16532721, 0.51597452])

In [73]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [74]:
np.random.rand(3,5)

array([[0.19861516, 0.27877011, 0.74811369, 0.8708952 , 0.89229461],
       [0.35289925, 0.00659998, 0.7832052 , 0.62370035, 0.67831569],
       [0.03648897, 0.57952073, 0.52995265, 0.44111188, 0.60164555]])

In [75]:
np.random,randint(4,6)

NameError: name 'randint' is not defined

In [76]:
np.random.randint(2,20,4)   #2nd argument  is exlusive

array([ 6, 19, 16,  7], dtype=int32)

In [77]:
np.random.randint(0,1)

0

In [78]:
np.random.randint(10,20,5)

array([11, 18, 18, 19, 17], dtype=int32)

In [79]:
np.random.randint(1,6,4)

array([2, 3, 2, 1], dtype=int32)

In [80]:
np.random.rand(3)

array([0.65486903, 0.36067604, 0.25613377])

In [81]:
np.random.randint(1)

0

In [82]:
np.random.randint(30,20,10)

ValueError: low >= high

In [83]:
np.random.randint(-30,20,10)

array([  0,   0, -14,  -1, -16, -11,  12, -20,  -4, -17], dtype=int32)

In [84]:
np.random.randint(20,30,10)

array([25, 26, 22, 27, 28, 24, 26, 23, 23, 24], dtype=int32)

In [85]:
np.random.randint(5,9)  #GET THE VALUE <=1&>=5

6

In [86]:
np.random.randint(10,21,3)

array([20, 20, 12], dtype=int32)

In [87]:
np.random.randint(1,21,3)

array([19,  6, 14], dtype=int32)

In [88]:
np.random.randint(1,12,3)

array([7, 5, 8], dtype=int32)

In [90]:
np.random.randint(10,40,(10,10))  #generate the element 10 -30 with 4*4 matrix

array([[30, 34, 30, 13, 23, 21, 22, 34, 33, 38],
       [28, 13, 29, 37, 12, 22, 23, 21, 29, 28],
       [14, 23, 28, 23, 19, 33, 36, 37, 14, 23],
       [29, 33, 11, 10, 21, 33, 12, 28, 22, 39],
       [37, 17, 11, 17, 39, 34, 18, 35, 13, 23],
       [20, 34, 32, 16, 26, 22, 36, 15, 30, 15],
       [25, 10, 10, 24, 31, 28, 28, 39, 22, 28],
       [21, 30, 21, 31, 12, 35, 31, 22, 21, 34],
       [15, 16, 26, 24, 22, 34, 38, 12, 35, 25],
       [39, 24, 27, 19, 35, 23, 15, 33, 30, 39]], dtype=int32)

In [92]:
np.random.randint(1,100,(12,12))  #generate the element 10 -30 with 4*4 matrix

array([[83,  6, 62, 22, 45, 15, 23, 88, 77, 40, 12, 51],
       [21, 28, 13, 88, 58, 69, 90, 96, 63, 57, 91, 71],
       [78, 13, 46, 54, 81, 74, 52, 65, 53, 83, 92, 13],
       [97,  1, 86, 76,  8,  6, 39,  5, 50, 13, 82,  5],
       [73, 33, 25, 88, 99, 71, 36, 68, 74, 76, 59, 14],
       [68, 52, 66, 69, 10, 71, 29, 14, 11, 49, 82, 96],
       [80, 10,  1, 35, 20, 41, 24,  8, 44,  2, 21, 77],
       [45,  7, 14, 65, 26,  7, 86, 92, 64, 48, 95, 81],
       [65, 84, 36, 51, 29, 38, 95, 40, 95,  6, 17, 28],
       [68, 37, 69, 20, 28, 26, 28, 24, 31, 16, 67, 30],
       [51, 16, 71, 23, 51, 56, 84, 64,  5, 58, 68, 74],
       [60, 99, 72, 88, 13, 36, 87, 98, 23, 73, 76,  6]], dtype=int32)

In [93]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [94]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [97]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [98]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Slicing in Matrix 

In [99]:
b=np.random.randint(10,20,(5,4))
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [100]:
type(b)

numpy.ndarray

In [101]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [102]:
b[:]

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [103]:
b[1:3]

array([[12, 12, 10, 17],
       [16, 11, 18, 17]], dtype=int32)

In [104]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [105]:
b[1,2]

np.int32(10)

In [106]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [107]:
b[1,3]

np.int32(17)

In [108]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [109]:
b[1,-1]

np.int32(17)

In [110]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [111]:
b[2:3]

array([[16, 11, 18, 17]], dtype=int32)

In [112]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [113]:
b[0:-2]

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17]], dtype=int32)

In [114]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [115]:
b[0,2]

np.int32(14)

In [116]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [117]:
b[-5,-3]

np.int32(10)

In [118]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [119]:
b[-4,2]

np.int32(10)

In [120]:
np.random.randint(10,20,(4,4))

array([[17, 12, 11, 14],
       [10, 19, 10, 19],
       [12, 19, 12, 12],
       [14, 18, 10, 19]], dtype=int32)

In [121]:
b

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

In [122]:
b[-4,-2]

np.int32(10)

In [123]:
b[:]

array([[12, 10, 14, 12],
       [12, 12, 10, 17],
       [16, 11, 18, 17],
       [16, 17, 11, 13],
       [19, 11, 14, 13]], dtype=int32)

# Operations 

In [124]:
a=np.random.randint(10,20,10)
a

array([10, 10, 18, 17, 17, 13, 12, 14, 14, 15], dtype=int32)

In [125]:
id(a)

1899669762288

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [128]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [129]:
arr

array([0, 1, 2, 3, 4, 5])

In [130]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [131]:
arr

array([0, 1, 2, 3, 4, 5])

In [132]:
arr[:4]

array([0, 1, 2, 3])

In [133]:
arr2[:]

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [134]:
arr2[0:5]

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82]], dtype=int32)

In [135]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [136]:
arr2[1,4]

np.int32(79)

In [137]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [138]:
arr2[5,-5]

np.int32(46)

In [139]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [140]:
arr2[-5,-5]

np.int32(46)

In [141]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [142]:
arr2[-1,-2]

np.int32(39)

In [143]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [145]:
arr2[::-1]

array([[64, 34, 99, 22, 63, 90, 32, 67, 39, 49],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [76, 10, 31, 41, 46, 34, 81, 99, 65, 89]], dtype=int32)

In [146]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [147]:
arr2[::-2]

array([[64, 34, 99, 22, 63, 90, 32, 67, 39, 49],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36]], dtype=int32)

In [148]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [149]:
arr2[::-3]

array([[64, 34, 99, 22, 63, 90, 32, 67, 39, 49],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [76, 10, 31, 41, 46, 34, 81, 99, 65, 89]], dtype=int32)

In [150]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [151]:
arr2[:-3]

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82]], dtype=int32)

In [152]:
arr2

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [84, 62, 93, 97, 79, 30, 92,  2, 85, 36],
       [90, 96, 41, 22, 18,  6, 45, 83, 63, 99],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [154]:
arr2[0:10:3]

array([[76, 10, 31, 41, 46, 34, 81, 99, 65, 89],
       [95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [155]:
arr2[3:]

array([[95, 98, 70, 49, 50, 86, 50, 59, 57, 11],
       [22, 77, 91, 73, 66, 41, 27, 62, 12, 82],
       [17,  7, 30, 68, 19, 46, 18, 90, 41, 91],
       [14,  3, 57, 26, 97,  7,  7, 88, 66, 82],
       [25, 82, 25, 45, 49, 94, 92, 61, 80, 61],
       [18, 13, 51, 80, 41, 38, 59,  0, 40, 61],
       [64, 34, 99, 22, 63, 90, 32, 67, 39, 49]], dtype=int32)

In [156]:
arr

array([0, 1, 2, 3, 4, 5])

In [157]:
arr.max()

np.int64(5)

In [158]:
arr.min()

np.int64(0)

In [159]:
arr

array([0, 1, 2, 3, 4, 5])

In [160]:
arr.mean()

np.float64(2.5)

In [161]:
arr

array([0, 1, 2, 3, 4, 5])

In [162]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [163]:
from numpy import*  #256 function called internally
a=array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Without work on import*.Find the median,mode 

In [164]:
arr

array([0, 1, 2, 3, 4, 5])

In [165]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [166]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [167]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [168]:
arr

array([0, 1, 2, 3, 4, 5])

In [169]:
arr.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [170]:
arr

array([0, 1, 2, 3, 4, 5])

In [171]:
arr.reshape(3,2,order='c')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [172]:
arr.reshape(2,3,order='c')  #print element with fortan

array([[0, 1, 2],
       [3, 4, 5]])

In [173]:
arr.reshape(2,3,order='A')  #A almost five you c type output

array([[0, 1, 2],
       [3, 4, 5]])

In [176]:
#import Numpy package
import numpy as np

#creating a Numpy array
num_array=np.arange(100).reshape(20,5)
print(num_array)

#Display array in Fortan order

print("\n C type array:")
for num_array in np.nditer(num_array,order="c"):
    print(num_array,end='')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

 C type array:
0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899

In [182]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 1 6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96 2 7 12 17 22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97 3 8 13 18 23 28 33 38 43 48 53 58 63 68 73 78 83 88 93 98 4 9 14 19 24 29 34 39 44 49 54 59 64 69 74 79 84 89 94 99 

In [183]:
arr.

SyntaxError: invalid syntax (1696555592.py, line 1)

In [184]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [187]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [186]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [188]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [189]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [190]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [191]:
arr

array([0, 1, 2, 3, 4, 5])

In [192]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing 

In [193]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
row=4
col=5
col


5

In [199]:
row

4

In [200]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [201]:
mat[row,col]

np.int64(45)

In [202]:
mat[4,5]

np.int64(45)

In [203]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [204]:
may[:]

NameError: name 'may' is not defined

In [207]:
col=6
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
mat[7]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [209]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
#with slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [211]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [212]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [213]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [214]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [215]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [216]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [217]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [218]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [219]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [220]:
row

4

In [221]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [222]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [224]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [225]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [226]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [227]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [228]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [229]:
row

4

In [230]:
col

6

In [231]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [232]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [233]:
mat[1,4]

np.int64(14)

In [234]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [235]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [236]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [237]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [239]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [240]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [241]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [242]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [243]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [244]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [245]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [246]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [247]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [248]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [249]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [250]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [251]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [252]:
mat[0,1]

np.int64(1)

In [254]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [255]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [256]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [257]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [258]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [259]:
mat[3,5]

np.int64(35)

In [260]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [261]:
mat[1:,2:4]

array([[12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [262]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [263]:
mat[2:3,2:3]

array([[22]])

In [264]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [265]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [266]:
mat[2:3,4:5]

array([[24]])

# Masking 

In [267]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [268]:
id(mat)

1899672395024

In [269]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [270]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [271]:
mat[mat==50]

array([50])

In [272]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [273]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [274]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [275]:
a3=mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [276]:
a4=mat[mat==50]
a4

array([50])

# Python program to generate otp 

In [277]:
import random
def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits='012345'
    otp=''.join(random.choice(digits) for_in range(length))
    return otp


#Example usage
otp_length=4  #You can change this to any length you prefer
otp=generate_otp(otp_length)
print(f"Your OTP is:{otp}")

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1103248525.py, line 5)

In [ ]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')