In [2]:
import numpy as np
np.__version__

'2.3.5'

In [1]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(array)

NameError: name 'array' is not defined

In [8]:
np.arange(10) # arange function it will print the value within interval

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

In [10]:
np.arange(10,20,5)

array([10, 15])

In [11]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [12]:
np.zeros(5)  #parameter tunning


array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5,dtype=int)  #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [14]:
np.zeros([2,2],dtype=int) #2d array

array([[0, 0],
       [0, 0]])

In [15]:
np.zeros([5,10],dtype=int) 


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones([3,5],dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(20,10)

array([], dtype=int64)

In [21]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [22]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [23]:
random.rand(3,2)

NameError: name 'random' is not defined

In [24]:
np.random.rand(2)

array([0.56624374, 0.1403373 ])

In [25]:
np.random.rand(5)


array([0.9060767 , 0.35720578, 0.42030154, 0.58464456, 0.39476387])

In [26]:
np.random.rand(3,2)

array([[0.56053549, 0.25128059],
       [0.27260474, 0.71119788],
       [0.25555012, 0.2759685 ]])

In [27]:
np.random.randint(3)

2

In [28]:
np.random.randint(5,10)

6

In [29]:
np.random.randint(5,10,3)

array([8, 9, 9], dtype=int32)

In [30]:

ra=np.random.randint(5,10,3)
print(ra)

[5 5 5]


In [31]:
otp=np.random.randint(5,10,4)
print(otp)

[5 9 5 7]


In [32]:
 arr0=np.random.randint(10,40,(10,10))
 print(arr10)

NameError: name 'arr10' is not defined

In [33]:
arr0

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [34]:
arr1=np.random.randint(1,5,(3,3))
print(arr1)

[[2 1 2]
 [1 2 2]
 [4 1 1]]


# comma(,), indexing,slicing in array   

In [35]:
arr1[:]

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [36]:
len(arr1)

3

In [37]:
arr1.shape

(3, 3)

In [38]:
arr0.shape

(10, 10)

In [39]:
len(arr0)

10

In [40]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [41]:
arr1[0]   #print row

array([2, 1, 2], dtype=int32)

In [42]:
arr1[1]  #print row

array([1, 2, 2], dtype=int32)

In [43]:
arr1[2]  #print row

array([4, 1, 1], dtype=int32)

In [44]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [45]:
arr1[:,1]  #print coiumn

array([1, 2, 1], dtype=int32)

In [46]:
arr[:,0]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [47]:
arr1[:,2]  #print column

array([2, 2, 1], dtype=int32)

In [48]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [49]:
arr1[0]

array([2, 1, 2], dtype=int32)

In [50]:
v=arr1[1,2]
print(v)

2


In [51]:
arr0

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [52]:
arr0[-7]

array([31, 24, 31, 14, 37, 24, 36, 24, 31, 37], dtype=int32)

In [53]:
arr0[:,-7]

array([22, 21, 21, 14, 22, 21, 13, 20, 26, 10], dtype=int32)

In [54]:
arr0

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [55]:
arr0[3:4,2:6]

array([[31, 14, 37, 24]], dtype=int32)

In [56]:
arr0[5:6,7:8]

array([[28]], dtype=int32)

In [57]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [58]:
arr1[1]

array([1, 2, 2], dtype=int32)

In [59]:
arr1[1,2]  #1 first row& 2 means columns

np.int32(2)

In [61]:
arr1[1:2]
    

array([[1, 2, 2]], dtype=int32)

In [62]:
print(arr)

[0 1 2 3 4 5]


In [63]:
print(arr1)

[[2 1 2]
 [1 2 2]
 [4 1 1]]


In [64]:
print(arr0)

[[35 14 20 22 37 23 28 15 14 14]
 [12 20 30 21 14 33 26 36 11 34]
 [37 16 25 21 12 35 11 25 13 15]
 [31 24 31 14 37 24 36 24 31 37]
 [13 36 13 22 11 20 12 38 31 24]
 [38 22 16 21 32 20 20 28 20 12]
 [16 14 36 13 32 21 27 14 18 17]
 [14 38 16 20 39 18 13 22 34 27]
 [11 14 22 26 19 30 14 37 14 14]
 [18 34 14 10 12 35 25 36 10 19]]


In [67]:
arr0[::3]

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [68]:
arr0

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [69]:
arr0[0:10:5]

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12]], dtype=int32)

In [70]:
arr0

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [71]:
arr0[::-1]

array([[18, 34, 14, 10, 12, 35, 25, 36, 10, 19],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [35, 14, 20, 22, 37, 23, 28, 15, 14, 14]], dtype=int32)

In [72]:
arr0

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [74]:
arr0[::-3]

array([[18, 34, 14, 10, 12, 35, 25, 36, 10, 19],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [35, 14, 20, 22, 37, 23, 28, 15, 14, 14]], dtype=int32)

In [76]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [78]:
arr1[1,2]  #specific number

np.int32(2)

In [80]:
arr1[1:2]

array([[1, 2, 2]], dtype=int32)

In [81]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [83]:
arr1[:,2]

array([2, 2, 1], dtype=int32)

# Reshaping 

In [84]:
arr

array([0, 1, 2, 3, 4, 5])

In [85]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [86]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 6 into shape (4,4)

In [87]:
arr

array([0, 1, 2, 3, 4, 5])

In [88]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [89]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [90]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [91]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [4, 1, 1]], dtype=int32)

In [93]:
arr1[0:2,1:3]

array([[1, 2],
       [2, 2]], dtype=int32)

# Masking or filter in matrix 

In [94]:
arr0

array([[35, 14, 20, 22, 37, 23, 28, 15, 14, 14],
       [12, 20, 30, 21, 14, 33, 26, 36, 11, 34],
       [37, 16, 25, 21, 12, 35, 11, 25, 13, 15],
       [31, 24, 31, 14, 37, 24, 36, 24, 31, 37],
       [13, 36, 13, 22, 11, 20, 12, 38, 31, 24],
       [38, 22, 16, 21, 32, 20, 20, 28, 20, 12],
       [16, 14, 36, 13, 32, 21, 27, 14, 18, 17],
       [14, 38, 16, 20, 39, 18, 13, 22, 34, 27],
       [11, 14, 22, 26, 19, 30, 14, 37, 14, 14],
       [18, 34, 14, 10, 12, 35, 25, 36, 10, 19]], dtype=int32)

In [96]:
arr0<20


array([[False,  True, False, False, False, False, False,  True,  True,
         True],
       [ True, False, False, False,  True, False, False, False,  True,
        False],
       [False,  True, False, False,  True, False,  True, False,  True,
         True],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [ True, False,  True, False,  True, False,  True, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
         True],
       [ True,  True, False,  True, False, False, False,  True,  True,
         True],
       [ True, False,  True, False, False,  True,  True, False, False,
        False],
       [ True,  True, False, False,  True, False,  True, False,  True,
         True],
       [ True, False,  True,  True,  True, False, False, False,  True,
         True]])

In [97]:
arr0[arr0<20]


array([14, 15, 14, 14, 12, 14, 11, 16, 12, 11, 13, 15, 14, 13, 13, 11, 12,
       16, 12, 16, 14, 13, 14, 18, 17, 14, 16, 18, 13, 11, 14, 19, 14, 14,
       14, 18, 14, 10, 12, 10, 19], dtype=int32)

In [98]:
arr0[arr0==20]

array([20, 20, 20, 20, 20, 20, 20], dtype=int32)

In [99]:
arr0[arr0 !=20]

array([35, 14, 22, 37, 23, 28, 15, 14, 14, 12, 30, 21, 14, 33, 26, 36, 11,
       34, 37, 16, 25, 21, 12, 35, 11, 25, 13, 15, 31, 24, 31, 14, 37, 24,
       36, 24, 31, 37, 13, 36, 13, 22, 11, 12, 38, 31, 24, 38, 22, 16, 21,
       32, 28, 12, 16, 14, 36, 13, 32, 21, 27, 14, 18, 17, 14, 38, 16, 39,
       18, 13, 22, 34, 27, 11, 14, 22, 26, 19, 30, 14, 37, 14, 14, 18, 34,
       14, 10, 12, 35, 25, 36, 10, 19], dtype=int32)

In [100]:
arr0[arr0>35]

array([37, 36, 37, 37, 36, 37, 36, 38, 38, 36, 38, 39, 37, 36],
      dtype=int32)

In [101]:
arr

array([0, 1, 2, 3, 4, 5])

In [102]:
max(arr)

np.int64(5)

In [103]:
min(arr)

np.int64(0)