#  NUMPY CODE:- 

# 1. ... 

In [123]:
import numpy as np

In [124]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])  #THIS IS 1D ARRAY

newarr1=arr.reshape(2,3,2)  #WITH RESHAPE FUNCTION NOW CONVERTED IT INTO 3D ARRAY
newarr2=arr.reshape(4,3)  #WITH RESHAPE FUNCTION NOW CONVERTED IT INTO 2D ARRAY - not required now.

print(newarr1)

print(newarr2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [125]:
newarr1

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [126]:
newarr1=[...,2]
print(newarr1)

[Ellipsis, 2]


In [127]:
newarr1=[1,...]
print(newarr1)

[1, Ellipsis]


# 2.[] 

In [128]:
import numpy as np
b=np.arange(0,20)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [129]:
b1=np.reshape(b,(5,4))
print(b1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [130]:
b1[0,0]

np.int64(0)

In [131]:
b1[-1]

array([16, 17, 18, 19])

In [132]:
b1[1:3,1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [133]:
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [134]:
b1>15

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [135]:
b<=15

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False])

In [136]:
a=np.array([[0,1,2,3,4],[10,11,12,13,14],[20,21,22,23,24],[30,31,32,33,34]])
c=np.array([True,False,True,False])  #boolean row selector
print(a)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [137]:
a[c,:]

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24]])

In [138]:
d=np.array([False,True,True,False,True]) #boolean coiumn selector
a[:,d]

array([[ 1,  2,  4],
       [11, 12, 14],
       [21, 22, 24],
       [31, 32, 34]])

In [139]:
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [140]:
i=np.array([0,1,2,1])  #array of indices for the first axis
j=np.array([1,2,3,4])  #array of indices for the second axis
a[i,j]

array([ 1, 12, 23, 14])

# 3.abs()&4.ABSOLUTE-both are same-Synonym for abs() 

In [141]:
import numpy as np
ARR=np.arange(-4,5).reshape(3,3)
ARR

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [142]:
abs(ARR)

array([[4, 3, 2],
       [1, 0, 1],
       [2, 3, 4]])

In [143]:
ARR1=1.2+5j
ARR1

(1.2+5j)

In [144]:
abs(ARR1)  #UNDER-ROOT OF square of real part & imaginary part

5.141984052872976

In [145]:
np.absolute(ARR1)

np.float64(5.141984052872976)

In [146]:
np.absolute([-10,-15])

array([10, 15])

# 5.Accumulate 

-computes the sum of given initial value and the elements in the given range

In [147]:
import numpy as np

In [148]:
A1=np.arange(0,10)
print(A1)

[0 1 2 3 4 5 6 7 8 9]


In [149]:
np.add.accumulate(A1)  #Progressive SUM

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [150]:
A2=np.arange(1,16)
np.multiply.accumulate(A2)

array([            1,             2,             6,            24,
                 120,           720,          5040,         40320,
              362880,       3628800,      39916800,     479001600,
          6227020800,   87178291200, 1307674368000])

In [151]:
AC=np.array([[1,2,3],[4,5,6]])
AC

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
np.add.accumulate(AC)

array([[1, 2, 3],
       [5, 7, 9]])

In [153]:
np.multiply.accumulate(AC)

array([[ 1,  2,  3],
       [ 4, 10, 18]])

# 6.add 

In [154]:
import numpy as np

In [155]:
ar1=[2,-6]
ar2=[1,3]
ar3=[2.2,8.7]
ar4=[7,-3]
print(ar1,ar2,ar3,ar4)

[2, -6] [1, 3] [2.2, 8.7] [7, -3]


In [156]:
np.add(ar1,ar2)

array([ 3, -3])

In [157]:
np.add(ar3,ar4)

array([9.2, 5.7])

In [158]:
c1=5+2j

In [159]:
np.add(ar3,c1)

array([ 7.2+2.j, 13.7+2.j])

# 7.all 

In [160]:
.Test wheather all array elements along a given axis evaulate to True


SyntaxError: invalid syntax (2406012062.py, line 1)

In [161]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
np.all(a>5)

np.False_

In [163]:
np.all(a>=0)

np.True_

In [164]:
b7=np.array([True,False,True,True])
np.all(b7)

np.False_

# 8.allclose 

In [165]:
-Returns True if two array are element-wise equal within a tolerance

SyntaxError: invalid syntax (921463798.py, line 1)

In [166]:
np.allclose([0.1,0.003],[0.11,0.003])

False

In [167]:
np.allclose([0.11,0.0033],[0.11000005,0.00330001])

True

In [168]:
np.allclose([1e10,1e-8],[1.0001e10,1e-9])


False

In [169]:
np.allclose([1e10,1e-8],[1.00001e10,1e-9])

True

# 9.alltrue- same as all function   

In [170]:
b = np.array([True,False,True,True])
np.all(b)

np.False_

In [171]:
a=np.array([1,5,2,7])
np.all(a>=5)

np.False_

In [172]:
np.all(a>0)

np.True_

# 10.angle 

In [173]:
-Returns the angle of the complex argument

SyntaxError: invalid syntax (3827965304.py, line 1)

In [174]:
np.angle([5+3j,1j,1.0])   #in RADIAN UNIT

array([0.5404195 , 1.57079633, 0.        ])

In [175]:
np.angle([5+3j,1j,1.0],deg=True)  #in Degree

array([30.96375653, 90.        ,  0.        ])

In [176]:
np.angle(1+1j,deg=False)   #in RADIAN Unit

np.float64(0.7853981633974483)

# 11.any 

In [177]:
-gives True if at least 1 element of a is True,otherwise  False

SyntaxError: invalid syntax (2774438772.py, line 1)

In [178]:
c2=np.array([True,False,True])
np.any(c2)

np.True_

In [179]:
c3=np.arange(0,10)
c3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
any(c3>=5)

True

# 12.append  

In [181]:
-Append values to the end of an array

SyntaxError: invalid syntax (895792348.py, line 1)

In [182]:
c3=np.append([1,2,3],[[4,5,6],[7,8,9]])
c3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
c5=np.append(c3,10)
c5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
np.append(c5,('ABC',1+2j))

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'ABC', '(1+2j)'],
      dtype='<U64')

In [185]:
c9=np.arange(10,61,10)
c9

array([10, 20, 30, 40, 50, 60])

In [186]:
np.append(c9,(70,80,90))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [187]:
c10=np.reshape(c9,(2,3))
c10

array([[10, 20, 30],
       [40, 50, 60]])

In [188]:
c11 = np.append(c10, [[70, 80, 90]], axis = 0)  # AT ROw
c11


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [189]:
c13=np.append(c11,[[100],[120],[130]],axis=1)  #AT COLUMN
c13

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 120],
       [ 70,  80,  90, 130]])

# 13.apply_along_axis 

In [190]:
-Apply a function to 1-D slices along the given axis

SyntaxError: invalid syntax (3156960793.py, line 1)

# It will apply function to axis 

In [191]:
def func1(Q)  : #EX-1
    return(Q[0]+Q[-1])
abc=np.array([[1,2,3],[4,5,6],[7,8,9]])
abc

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [192]:
np.apply_along_axis(func1,0,abc)  #When AXIS=0 apply func1 to each COLUMN of abc

array([ 8, 10, 12])

In [193]:
np.apply_along_axis(func1,1,abc)  #When AXIS=1 apply func1 to each ROW of abc

array([ 4, 10, 16])

In [194]:
def  func2(p):  #2
    return(p[0]+p[-1])*2
abc1=np.array([[1,2,3],[4,5,6],[7,8,9]])
abc1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
np.apply_along_axis(func2,0,abc1)  #When  AXIS=0 apply func1 to each COLUMN of abc

array([16, 20, 24])

In [196]:
np.apply_along_axis(func2,1,abc1)  #When AXIS=1 apply func1 to each ROW of abc

array([ 8, 20, 32])

# 14.apply_over_axis 

In [197]:
-The numpy.apply_over_axes() applies a function repeatedly over multiple axes in an array

SyntaxError: invalid syntax (616686383.py, line 1)

In [198]:
D=np.arange(24)
D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [199]:
D=np.reshape(D,(2,3,4))
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [200]:
DQ=np.apply_over_axes(np.sum,D,[0,2])   #sum over all axes except axis=1,result has same shape as original
DQ

array([[[ 60],
        [ 92],
        [124]]])

# 15.arrange 

In [201]:
-Return evenly spaced values within a given interval

SyntaxError: invalid syntax (1880891920.py, line 1)

In [202]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [203]:
np.arange(11.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [204]:
np.arange(8,dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [205]:
np.arange(5,10)  #star,stop

array([5, 6, 7, 8, 9])

In [206]:
np.arange(3,30,9)  #start,stop,step

array([ 3, 12, 21])

# 16.acccos 

In [207]:
-Trigonmetric inverse cosine
-The inverse of cos so that,if y=cos(x),then x=across(y)

SyntaxError: invalid syntax (2652807346.py, line 1)

In [208]:
np.arccos([1,-1])   #we except the arccos of 1 to be 0,and of -1 to be pi:

array([0.        , 3.14159265])

# 17.arccosh 

In [209]:
-Inverse hyperbolic cosine

SyntaxError: invalid syntax (2555609711.py, line 1)

In [210]:
np.arccosh([np.e,10.0])

array([1.65745445, 2.99322285])

In [211]:
np.arccosh(1)

np.float64(0.0)

# 18.arcsin 

In [212]:
-Inverse hyperbolic sine

SyntaxError: invalid syntax (1412783537.py, line 1)

In [213]:
np.arcsin([1,-1,0])

array([ 1.57079633, -1.57079633,  0.        ])

# 19.arcsinh 

In [214]:
-Inverse hypewrbolic Sine

SyntaxError: invalid syntax (4290230673.py, line 1)

In [215]:
np.arcsinh([np.e,10.0])

array([1.72538256, 2.99822295])

# 20.arctan 

In [216]:
-Trigonmetric inverse tangent,element-wise
The inverse of tan,so that if y=tan(x) then x=arctan(y)


SyntaxError: invalid syntax (4175811214.py, line 1)

In [217]:
np.arctan([0,1,-1])

array([ 0.        ,  0.78539816, -0.78539816])

# 21.arctan2  

In [218]:
It computes element-wise arc tangent of arr1/arr2 choosing the quardant correctly.
The quardant is chosen so that arctan2(x1,x2)

SyntaxError: invalid syntax (3743310217.py, line 1)

In [219]:
#consider four points in different quardrants
x=np.array([-1,+1,+1,-1])
y=np.array([-1,-1,+1,+1])
np.arctan2(y,x)*180/np.pi   #In Degree Unit

array([-135.,  -45.,   45.,  135.])

In [220]:
np.arctan2(y,x)  #IN radian unit

array([-2.35619449, -0.78539816,  0.78539816,  2.35619449])

In [221]:
np.arctan2([1.,-1.],[0.,0.])

array([ 1.57079633, -1.57079633])

In [222]:
np.arctan2([0,1],[1,0])

array([0.        , 1.57079633])

# 22.arctanh 

In [223]:
-Inverse hyperbolic tangent

SyntaxError: invalid syntax (1016660218.py, line 1)

In [224]:
np.arctanh([0,-0.5])

array([ 0.        , -0.54930614])

# 23.argmax 

In [225]:
-Returns the indices of the maximum values along an axis

SyntaxError: invalid syntax (1080949910.py, line 1)

In [226]:
J=np.array([0,11,95,2,-5,55])
np.argmax(J)

np.int64(2)

In [227]:
j1=np.arange(6).reshape(2,3)  +10
j1

array([[10, 11, 12],
       [13, 14, 15]])

In [233]:
np.argmax(j1)

np.int64(5)

In [234]:
j2=np.array([[10,50,30],[60,20,60]])  #If having more than 1 maximum values it will right 1st index----NOTE

In [236]:
J2=np.array([[1,9,0,4],[2,0,8,-1]])

In [231]:
np.argmax(J2, axis=0)   #for each column:the row index of the maximum value

array([1, 0, 1, 0])

In [237]:
np.argmax(J2,axis=1)   #for each row:the column indexof the maximum value

array([1, 2])

# 24.argmin 

In [ ]:
-Returns the indices of the Minimum values along an axis

In [239]:
d4=np.array([0,11,95,2,-5,55])
np.argmin(d4)

np.int64(4)

In [240]:
d9=np.arange(6).reshape(2,3) +10
d9

array([[10, 11, 12],
       [13, 14, 15]])

In [241]:
np.argmin(d9)

np.int64(0)

In [242]:
da2=np.array([[50,50,10],[60,10,40]])
da2

array([[50, 50, 10],
       [60, 10, 40]])

In [243]:
np.argmin(da2)   #if having more than 1min. vales it will right 1st index-----NOTE

np.int64(2)

In [244]:
np.argmin(da2,axis=0)   #for each column:the row index of the maximum value

array([0, 1, 0])

In [245]:
np.argmin(da2,axis=1)   #for each row:the column index of the maximum value

array([2, 1])

# 25.argsoft 

In [ ]:
-Returns the indicates that would sort an array

In [246]:
AB1=np.array([2,0,1,5,4,1,9])
np.argsort(AB1)

array([1, 2, 5, 0, 4, 3, 6])

In [247]:
# FOR SORTING OF VALUES
BQ=np.argsort(AB1)
BQ

array([1, 2, 5, 0, 4, 3, 6])

In [248]:
AB1[BQ]  #same effect as sort() but on values

array([0, 1, 1, 2, 4, 5, 9])

In [249]:
aq1=np.array([[8,4,1],[2,0,9]])
aq1

array([[8, 4, 1],
       [2, 0, 9]])

In [250]:
JQ1=aq1.argsort(axis=0)  #sorts on columns.NOT the same as aq1.sort(axis=1)
JQ1

array([[1, 1, 0],
       [0, 0, 1]])

In [254]:
aq1[JQ1,[[0,1,2],[0,1,2]]]  #2-D arrays need fancy indexing if you want to sort them.
aq1

array([[8, 4, 1],
       [2, 0, 9]])

In [255]:
JQ1=aq1.argsort(axis=1)  #sort along rows.Can use aq1.argsort(axis=-1) for last axis
JQ1


array([[2, 1, 0],
       [1, 0, 2]])

# 26.array 

In [ ]:
. To Create an array.

In [256]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [262]:
np.array([[1, 2], [3, 4]]) # More than one dimension:

array([[1, 2],
       [3, 4]])

In [263]:
np.array([1,2,3],dtype=complex) #type provided:

array([1.+0.j, 2.+0.j, 3.+0.j])

In [268]:
np.array([1 ,2, 3], ndmin=2) # Minimum dimension 2:

array([[1, 2, 3]])

In [273]:
np.array(1, copy=0, subok=1, ndmin=1) # basically equivalent to atleast_1d

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

In [274]:
np.array(1,copy=0,subok=1,ndmin=2)    #basically equivalent toatleast_2D

ValueError: Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword.

In [275]:
np.array(1,subok=1,ndmin=2)  #Like atleast_2d but always makes a copy

array([[1]])

# 27.arrayrange 

In [ ]:
-Synonym for arrange

#  28.array split 

In [ ]:
-Split an array into multiple sub-arrays

In [276]:
c4=np.array([[1,2,3,4],[5,6,7,8]])
c4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [277]:
np.array_split(c4,2,axis=0)  #split c4 in 2 patrs.row-wise

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [278]:
np.array_split(c4,2,axis=1)  #split c4 in 4 parts,column-wise

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [279]:
np.array_split(c4,3,axis=1)  #impossible to split in 3 equal parts ->first parts(s) are bigg

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [280]:
np.array_split(c4,[2,3],axis=1)   #make c4 split before the 2nd and the 3rd column

[array([[1, 2],
        [5, 6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

# 29.asarray 

In [ ]:
-Convert the input to an array

In [281]:
my_list=[1,3,5,7,9]
np.asarray(my_list)   #list to array for this example

array([1, 3, 5, 7, 9])

In [282]:
my_tuple=([1,3,9],[8,2,6])
np.asarray(my_tuple)  #tuple to array for this example

array([[1, 3, 9],
       [8, 2, 6]])

In [283]:
m=np.matrix('1 2;5 8')
m

matrix([[1, 2],
        [5, 8]])

In [284]:
B9=np.asarray(m)  # a is array type with same contents as m--data is not copied
B9

array([[1, 2],
       [5, 8]])

In [285]:
m[0,1]=-190
m

matrix([[   1, -190],
        [   5,    8]])

In [286]:
B9

array([[   1, -190],
       [   5,    8]])

#  30.asanyarray  

In [ ]:
-convert the input to an ndarray,but pass ndarray subclasses through

In [287]:
c7=np.array([[1,2],[5,8]])
c7

array([[1, 2],
       [5, 8]])

In [288]:
mq=np.matrix('1 2;5 8')
mq

matrix([[1, 2],
        [5, 8]])

In [290]:
np.asanyarray(c7)

array([[1, 2],
       [5, 8]])

In [291]:
np.asanyarray(mq)

matrix([[1, 2],
        [5, 8]])

In [293]:
my_tuple1=([1,3,9],[8,2,6])
np.asanyarray(my_tuple1)

array([[1, 3, 9],
       [8, 2, 6]])

# 31.asmatrix 

In [ ]:
Interpret the input asa matrix

In [294]:
x=np.array([[1,2],[3,4]])
m=np.asmatrix(x)  #m is matrix type with same contents as x--data is not copied
m

matrix([[1, 2],
        [3, 4]])

In [296]:
x[0,0]=5
print(m)

print(x)

[[5 2]
 [3 4]]
[[5 2]
 [3 4]]


# 32.astype 

In [ ]:
Copy of the  array,cast to a specified type.

In [297]:
x6=np.array([1,2,2.5])
x6

array([1. , 2. , 2.5])

In [298]:
x6.astype(int)

array([1, 2, 2])

In [299]:
x6.astype(None)

array([1. , 2. , 2.5])

# 33.atleast 1d 

In [301]:
a01=1
b01=np.array([2,3])
c01=np.array([[4,5],[6,7]])
d01=np.arange(8).reshape(2,2,2)
d01

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [302]:
np.atleast_1d(a01,b01,c01,d01)

(array([1]),
 array([2, 3]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

#  34.atleast_2d ()

In [303]:
a11=1
b11=np.array([2,3])
c11=np.array([[4,5],[6,7]])
d11=np.arange(8).reshape(2,2,2)
d11

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [304]:
np.atleast_2d(a11,b11,c11,d11)

(array([[1]]),
 array([[2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]]))

# 35.atleast_3d() 

In [305]:
f=1 # 0-d array 
g=np.array([2,3]) # 2-d array 
h=np.array([[4,5],[6,7]]) # 3-d array 
i

array([0, 1, 2, 1])

In [306]:
np.atleast_3d(f,g,h,i) #all  output array have dim >=3

(array([[[1]]]),
 array([[[2],
         [3]]]),
 array([[[4],
         [5]],
 
        [[6],
         [7]]]),
 array([[[0],
         [1],
         [2],
         [1]]]))

# 36.Average 

Compute the weighted average along the specified axis.

In [307]:
bz=np.array([1,4,5,7,5])
bz

array([1, 4, 5, 7, 5])

In [308]:
np.average(bz)

np.float64(4.4)

In [310]:
 w=np.array([0.1, 0.2,0.5,0.2,0.2]) # weights,npt necessarily normslized

In [ ]:
np.average(bz,weights=w) # This will give weightd avg.=sum(Element*weight)/sum(weight